title: "Quantitative Tools for Qualitative Analysis: Computational Social Science meets Discourse Analysis"
description: A workshop at the European Symposium Series on Societal Challenges in Computational Social Science, London 2017
theme: jekyll-theme-minimal
github: [metadata]